import numpy as np, sys
z = np.load("ml/soiling_snn_export.npz")
NF, H, T, beta = int(z["NF"]), int(z["H"]), int(z["T"]), float(z["beta"])

def arr(name, a):
    a = np.asarray(a, np.float32).ravel()
    def fmt(v):
        t = f"{v:.9g}"
        if "." not in t and "e" not in t and "E" not in t and "inf" not in t:
            t += ".0"          # 39675f is an int constant; 39675.0f is a float
        return t + "f"
    body = ",".join(fmt(v) for v in a)
    return f"static const float {name}[{a.size}] = {{{body}}};\n"

h  = "// AUTO-GENERATED by gen_header.py -- do not edit\n#ifndef SOILING_SNN_H\n#define SOILING_SNN_H\n\n"
h += f"#define SNN_NF {NF}\n#define SNN_H  {H}\n#define SNN_T  {T}\n"
h += f"#define SNN_BETA {beta:.8g}f\n#define SNN_THRESH 1.0f\n\n"
h += arr("snn_f1_w", z["f1_w"])            # [H][NF]  row-major, dense matvec
h += arr("snn_f1_b", z["f1_b"])
h += arr("snn_f2_wT", z["f2_w"].T)         # [H_in][H_out] transposed for column access
h += arr("snn_f2_b", z["f2_b"])
h += arr("snn_out_w", z["out_w"])          # [1][H]
h += arr("snn_out_b", z["out_b"])
h += arr("snn_mu", z["mu"])
h += arr("snn_sd", z["sd"])
h += "\n#endif\n"
open("fw/soiling_snn.h","w").write(h)

g  = "// golden vectors from PyTorch (float32)\n#ifndef GOLDEN_H\n#define GOLDEN_H\n"
g += f"#define N_GOLDEN {z['golden_in'].shape[0]}\n"
g += arr("golden_in", z["golden_in"])      # [N][T][NF] RAW (un-normalised)
g += arr("golden_out", z["golden_out"])
g += "\n#endif\n"
open("fw/golden.h","w").write(g)
print("header bytes:", len(h), "| params:",
      z["f1_w"].size+z["f1_b"].size+z["f2_w"].size+z["f2_b"].size+z["out_w"].size+z["out_b"].size)
